### ISSUE TITLE
plz release the latest runtime for the dev branch

### ISSUE THREAD

**Issue by LegacyGamerHD** [AOF-Dev/MCinaBox#399] opened 2020-09-25 15:05 UTC
also if you guys need help i will offer it

**Comment by NidzGamingTV** [comment] 2020-09-25 15:47
Help them develop this app

**Comment by AyHa1810** [comment] 2020-09-25 16:28
I think at Minecraft@Home's discord, there are a lot of minecraft programmers. Idk if they will help or not.

**Comment by LegacyGamerHD** [comment] 2020-09-25 18:02
> I think at Minecraft@Home's discord, there are a lot of minecraft programmers. Idk if they will help or not.

@AyHa1810  ey suburo #rezero any i woeld help soonish as am also helping small things in pojav

**Comment by longjunyu2** [comment] 2020-09-26 08:26
@LegacyGamerHD  At present, there are still some problems in the loading strategy of the runtime. This causes minecraft 1.13 + to be unable to find the liblwjgl.so file. The new runtime will be released as soon as the problem is resolved.
As you can see, the project has been migrated to the development organization, and the next updates will be more active.
So, you can help improve the project at any time.

**Comment by AyHa1810** [comment] 2020-09-26 17:43
@longjunyu2 I think Minecraft 1.13+ requires lwjgl 3.2.2 to run properly. Because lwjgl 3.2.3 might have some graphics issue with Minecraft 1.13+. That's the reason why Minecraft 1.13+ is stuck on lwjgl 3.2.1 or 3.2.2.

**Comment by Dndrix** [comment] 2020-09-27 06:11
I have version 1.15.2-1.16.3 running ...
But less than one starts up

**Closed** 2020-10-10 09:56 UTC
