### ISSUE TITLE
1.16.1 crash on android 9

### ISSUE THREAD

**Issue by Tayoikoo** [AOF-Dev/MCinaBox#229] opened 2020-06-29 15:07 UTC
When i install 1.16.1 and it finished then open it.. after that the game crashes before Mojang loading screen. What happend?
I am using Android 9, 6GB ram, Snap 712

**Comment by bghyt** [comment] 2020-06-30 21:00
1.13 and up do not work correctly there are visual bugs that makes the game impossible to play, best to use 1.7.10 and 1.12.2 for the best results as they work as intended with the least crashes, also dedicate about 500-900mb of ram to the game.

**Comment by SnowNF** [comment] 2021-01-09 11:03
fixed in newset version.

**Closed by SnowNF** 2021-01-09 11:03 UTC
